#include <stdio.h>

int main()
{
    int n = 3;
    // int arr[n] = {10, 20, 30}; // that generated by error message.
    int arr[] = {10,20,30}; // that is correct form.
    printf("%d %d %d", arr[0], arr[1], arr[2]);
    return 0;
}